# Generated by Django 2.0.4 on 2018-04-20 08:36

import apps.base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=apps.base.fields.StatusField(default=True, verbose_name='active'),
        ),
    ]
